### ISSUE TITLE
ID generation should have a subset of characters

### ISSUE THREAD

**Issue by PossibleLlama** [PossibleLlama/worklog#70]
As a user, I want to be able to easily specify the ID of an item of Work.
This will make it easier to write down 

A generated ID should fit the regex `^[a-z0-9]{20}$`.

---

Changed generated ID to fit regex `^[a-f0-9]{20}$`.

**Comment by AlkaDas991** [comment]
@PossibleLlama Can you please elaborate the issue to better understand it? Thanks in advance

**Comment by PossibleLlama** [comment]
> @PossibleLlama Can you please elaborate the issue to better understand it? Thanks in advance

Sure 🙂 Other systems such as Docker have their ID's with all lowercase alphabetic characters, or numbers.

Currently the ID is any lowercase or uppercase alphabetic character.

It will hopefully be easier to select a specific item of Work with an ID that is similar to these kinds of ID's.

Other issues relate to using this ID to specify printing or editing Work by ID.
